# The URL the site will be built for
base_url = "https://stratis-storage.github.io"
theme = "hyde"
title = "Stratis Storage"
description = "Easy to use local storage management for Linux."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
highlight_code = true

[extra]
hyde_sticky = false
hyde_theme = "theme-base-10"
hyde_user_links = [
    {url = "$BASE_URL/howto", name = "How-To"},
    {url = "$BASE_URL/users", name = "Clients and Operating Systems"},
]
hyde_developer_links = [
    {url = "$BASE_URL/StratisSoftwareDesign.pdf", name = "Software Design"},
    {url = "$BASE_URL/DBusAPIReference.pdf", name = "D-Bus API Reference"},
    {url = "$BASE_URL/StratisStyleGuidelines.pdf", name = "Programming Style Guidelines"},
]
hyde_introspection_links = [
    {url = "$BASE_URL/manager.xml", name = "Manager object"},
    {url = "$BASE_URL/pool.xml", name = "Pool object"},
    {url = "$BASE_URL/filesystem.xml", name = "Filesystem object"},
    {url = "$BASE_URL/blockdev.xml", name = "Blockdev object"},
]
hyde_contact_links = [
    {url = "https://github.com/stratis-storage", name = "Github", fa="fab fa-github"},
    {url = "https://twitter.com/stratisstorage", name = "Twitter", fa="fab fa-twitter"},
]
